### ISSUE TITLE
扩展开启之后小组帖子里的评论无法点赞

### ISSUE THREAD

**Issue by Caelestrasz** [tcatche/douban-group-enhance#1]
功能建议：我的豆瓣小组中帖子默认用新窗口打开（有一个现成扩展但在我的小组页面失效）

**Comment by tcatche** [comment]
已添加此功能

**Comment by Caelestrasz** [comment]
不能点赞是还没修吗？
还有功能建议：显示楼层号，谢谢

**Comment by tcatche** [comment]
> 不能点赞是还没修吗？
> 还有功能建议：显示楼层号，谢谢

点赞不能复现，我这里试了，点赞是好的，确定是本插件的原因吗？

**Comment by Caelestrasz** [comment]
我又试了一下还是不行，开了插件点赞就不成功，关了就行

**Comment by tcatche** [comment]
> 我又试了一下还是不行，开了插件点赞就不成功，关了就行

更新了一版，你看看问题还存在吗，如果控制台有报错，麻烦贴一些错误

**Comment by Caelestrasz** [comment]
不好意思，表达不够准确，不是不能点赞帖子，是不能点赞帖子里的评论

(index):937 Uncaught TypeError: $.post_withck is not a function
    at HTMLAnchorElement.<anonymous> ((index):937)
    at HTMLUListElement.Ka (jquery.min.js:18)
    at HTMLUListElement.handle (jquery.min.js:63)
    at HTMLUListElement.o (jquery.min.js:56)

**Comment by tcatche** [comment]
> 不好意思，表达不够准确，不是不能点赞帖子，是不能点赞帖子里的评论
> 
> (index):937 Uncaught TypeError: $.post_withck is not a function
> at HTMLAnchorElement. ((index):937)
> at HTMLUListElement.Ka (jquery.min.js:18)
> at HTMLUListElement.handle (jquery.min.js:63)
> at HTMLUListElement.o (jquery.min.js:56)

谢谢反馈，已经查明原因修复了，请更新到最新版本 0.1.4 版本即可

**Comment by Caelestrasz** [comment]
好的解决了，这个插件已经很完美了
还有两个功能建议：
1、外链直接跳转，
2、加一个按钮直接跳转到评论，安卓按左下角能直接跳转到评论，不知道网页可不可以，不然主楼有图片一长翻起来挺费事的
不会烦我吧，谢谢开发大大，可以close了。

**Comment by tcatche** [comment]
> 好的解决了，这个插件已经很完美了
> 还有两个功能建议：
> 1、外链直接跳转，
> 2、加一个按钮直接跳转到评论，安卓按左下角能直接跳转到评论，不知道网页可不可以，不然主楼有图片一长翻起来挺费事的
> 不会烦我吧，谢谢开发大大，可以close了。

外链直接跳转 什么意思？

**Comment by Caelestrasz** [comment]
我找到一个了，就是豆瓣里的外部链接要确认一次，好像这不应该算在豆瓣小组插件里，谢谢了
https://greasyfork.org/zh-CN/scripts/378996-豆瓣外链免确认

**Comment by tcatche** [comment]
> 好的解决了，这个插件已经很完美了
> 还有两个功能建议：
> 1、外链直接跳转，
> 2、加一个按钮直接跳转到评论，安卓按左下角能直接跳转到评论，不知道网页可不可以，不然主楼有图片一长翻起来挺费事的
> 不会烦我吧，谢谢开发大大，可以close了。

页面左下角已经增加跳转，更新插件后开启此功能即可(○｀ 3′○)

**Comment by Caelestrasz** [comment]
好的，谢谢
