### ISSUE TITLE
超级好用，但是希望作者增加多一个功能

### ISSUE THREAD

**Issue by ghost** [tcatche/douban-group-enhance#2]
这个插件非常好用，但是希望作者增加多一个功能，也就是增加多一个选项，已看过的帖子可以设置为隐藏，因为有时候帖子数量多了，那么已经看过的帖子也会影响到自己所需要获取的信息，希望作者看看

**Comment by tcatche** [comment]
> 这个插件非常好用，但是希望作者增加多一个功能，也就是增加多一个选项，已看过的帖子可以设置为隐藏，因为有时候帖子数量多了，那么已经看过的帖子也会影响到自己所需要获取的信息，希望作者看看

看了下，由于浏览器的限制，只能把访问过的帖子标题字体尽量淡化，无法完全删除
已做淡化处理，更新即可

**Comment by ghost** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        谢谢
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                136838143
                            
                    
                        
                            
                                    136838143@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年4月23日 16:58，tcatche<notifications@github.com> 写道： 



这个插件非常好用，但是希望作者增加多一个功能，也就是增加多一个选项，已看过的帖子可以设置为隐藏，因为有时候帖子数量多了，那么已经看过的帖子也会影响到自己所需要获取的信息，希望作者看看

看了下，由于浏览器的限制，只能把访问过的帖子标题字体尽量淡化，无法完全删除
已做淡化处理，更新即可

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
