### ISSUE TITLE
在无痕模式下无法启用-油猴扩展已在隐身模式下启用

### ISSUE THREAD

**Issue by Caelestrasz** [tcatche/douban-group-enhance#3]
userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:2 ERROR: Execution of script '豆瓣小组功能增强' failed! Cannot read property 'include' of null
(anonymous) @ userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:2
(anonymous) @ userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:3
(anonymous) @ userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:396
(anonymous) @ userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:398
(anonymous) @ VM202:2
b @ VM202:1
E_u @ VM202:3
u @ VM214:65
ia @ VM214:63
create @ VM214:75
c @ VM214:16
setTimeout (async)
(anonymous) @ VM202:2
c.<computed> @ VM202:8
(anonymous) @ VM214:16
runListeners @ VM214:16
(anonymous) @ VM214:76
W @ VM202:10
e @ content.js:6
send @ content.js:8
(anonymous) @ content.js:27
processQueue @ content.js:3
a @ content.js:10
userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:2 TypeError: Cannot read property 'include' of null
    at initDomValue (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:373)
    at Object.init (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:385)
    at eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:394)
    at Window.eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:395)
    at <anonymous>:2:494
    at eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:2)
    at eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:3)
    at Object.eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:396)
    at eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:398)
    at eval (<anonymous>)

**Comment by tcatche** [comment]
> userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:2 ERROR: Execution of script '豆瓣小组功能增强' failed! Cannot read property 'include' of null
> (anonymous) @ userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:2
> (anonymous) @ userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:3
> (anonymous) @ userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:396
> (anonymous) @ userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:398
> (anonymous) @ VM202:2
> b @ VM202:1
> E_u @ VM202:3
> u @ VM214:65
> ia @ VM214:63
> create @ VM214:75
> c @ VM214:16
> setTimeout (async)
> (anonymous) @ VM202:2
> c. @ VM202:8
> (anonymous) @ VM214:16
> runListeners @ VM214:16
> (anonymous) @ VM214:76
> W @ VM202:10
> e @ content.js:6
> send @ content.js:8
> (anonymous) @ content.js:27
> processQueue @ content.js:3
> a @ content.js:10
> userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:2 TypeError: Cannot read property 'include' of null
> at initDomValue (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:373)
> at Object.init (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:385)
> at eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:394)
> at Window.eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:395)
> at :2:494
> at eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:2)
> at eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:3)
> at Object.eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:396)
> at eval (userscript.html?id=032baa47-7d5e-4c2d-9cc4-2b8282c52b42:398)
> at eval ()

感谢反馈，问题已经修复，请更新后再试试呢

**Comment by Caelestrasz** [comment]
好的，行了。还有一个问题，评论现在是跳转到最赞评论下面是吗？不知道大多数人使用习惯看不看最赞

**Comment by tcatche** [comment]
> 好的，行了。还有一个问题，评论现在是跳转到最赞评论下面是吗？不知道大多数人使用习惯看不看最赞

有“最赞”这个功能啊？没注意到=。=，回头有时间看一下
