### ISSUE TITLE
过滤相同 title 的帖子

### ISSUE THREAD

**Issue by takeTrace** [tcatche/douban-group-enhance#4]
有些人重复发帖的, 能不能过滤掉出现的饿相同 title 的帖子的啊

**Comment by Sunknomore** [comment]
您好 感谢分享 有一个问题是每次清理过浏览器之后设置就得重新选择 关键词也要重新输入 请问是否可以保存设置呢

**Comment by tcatche** [comment]
> 有些人重复发帖的, 能不能过滤掉出现的饿相同 title 的帖子的啊

这个不太好做，因为有几种特殊情况。
可能会存在 title 一样，作者不一样。
或者同一个作者有多个 title 一样
保留哪个，屏蔽哪个的问题不好处理，暂时先不予支持

**Comment by tcatche** [comment]
> 您好 感谢分享 有一个问题是每次清理过浏览器之后设置就得重新选择 关键词也要重新输入 请问是否可以保存设置呢

用户的配置是保存在本地的 localStorge。配置的管理，导入导出或配置同步处理起来比较麻烦，清理全部页面缓存也不是一个高频操作，暂时也没有计划做。

如果有需要清理全部缓存的场景，建议还是使用浏览器的无痕窗口比较好。

如果你了解 javascript 及浏览器控制台的话，可以在浏览器控制台使用 `localStorage.getItem('douban_group_enhance_config')` 将打印的配置备份，恢复的话执行 `localStorage.setItem('douban_group_enhance_config', 配置信息) `

**Comment by Sunknomore** [comment]
明白了 感谢回复(•ᴗ•)

Sent from my iPhone

On 23 May 2019, at 10:20, tcatche <notifications@github.com<mailto:notifications@github.com>> wrote:


您好 感谢分享 有一个问题是每次清理过浏览器之后设置就得重新选择 关键词也要重新输入 请问是否可以保存设置呢

用户的配置是保存在本地的 localStorge。配置的管理，导入导出或配置同步处理起来比较麻烦，清理全部页面缓存也不是一个高频操作，暂时也没有计划做。

如果有需要清理全部缓存的场景，建议还是使用浏览器的无痕窗口比较好。

如果你了解 javascript 及浏览器控制台的话，可以在浏览器控制台使用 localStorage.getItem('douban_group_enhance_config') 将配置备份，恢复的话执行 localStorage.setItem('douban_group_enhance_config', 配置信息)
