### ISSUE TITLE
按照 作者 屏蔽小组帖子

### ISSUE THREAD

**Issue by blueswhisper** [tcatche/douban-group-enhance#5]
我是用在豆瓣租房小组中的，知道现在各种租房小组都大量充斥着二房东，中介。

这些二房东，中介的特点就是会大量的发帖，自己评论刷新帖子活跃度。所以希望能够按照帖子作者屏蔽帖子。 至少能在一定程度上减少获取有效直租，转租信息的难度。

**Comment by tcatche** [comment]
看起来 greasyfork 已经有插件支持这个功能了
![image](https://user-images.githubusercontent.com/7147399/87403858-f9619900-c5ef-11ea-8bfa-dbb9069eeae2.png)
